{-# OPTIONS --guardedness #-}

------------------------------------------------------------------------
-- COST EXPERIMENT for `Semantics.FailureSim` at REAL scale.
--
-- `PipePairFlipBFs` proves `bfServer≈DRhi : BFserverA l hi ≈DR bfServerSpec l hi`
-- through `DRFromRel`, which demands SIX obligations.  Since
-- `P ≈FD Q = (P ⊑FD Q) × (Q ⊑FD P)`, the SECOND component of
-- `drbisim→≈FD (bfServer≈DRhi l)` is `bfServerSpec l hi ⊑FD BFserverA l hi`
-- — the "spec is refined by the impl" half.
--
-- This module obtains exactly that half through the ONE-WAY route:
-- `FSimFromRel` reuses `PipePairFlipBFs`'s relation `BFSRel` and its FORWARD
-- obligations `bfsFwdE` / `bfsFwdT` / `bfsNdivL` VERBATIM (imported, not copied),
-- and replaces `bfsBwdE` / `bfsBwdT` / `bfsNdivR` by ONE stability obligation
-- `bfsStab`.  The three backward obligations are never mentioned.
--
-- `orientation-check` pins the direction claim mechanically.
--
-- No postulates, holes, or `NON_TERMINATING` in this module.
------------------------------------------------------------------------

open import Level using (0ℓ; lower)
open import Data.Unit.Polymorphic using (⊤; tt)
open import Data.Maybe using (Maybe; just; nothing)
open import Data.Product using (_×_; _,_; Σ; Σ-syntax; proj₁; proj₂)
import Data.Fin as F
open import Data.Empty using (⊥; ⊥-elim)
open import Data.Sum using (_⊎_; inj₁; inj₂)
open import Relation.Nullary using (Dec; yes; no)
open import Relation.Binary.PropositionalEquality using (_≡_; refl)
open import Class.DecEq using (DecEq; _≟_)
open import Function.Base using (case_of_)

open import Process_Trees
open PTree

open import CSP.Examples.Cardano_network.FourNode.FourNodeDiamond using ( p )
open import CSP.Examples.Cardano_network.Params using (Params)
open Params p
open import CSP.Examples.Cardano_network.Base
open import CSP.Examples.Cardano_network.Data p
open import CSP.Examples.Cardano_network.Net p
open import CSP.Examples.Cardano_network.NetworkPar p
  using ( BFserverA; ιBF; ιBF⁻¹; ιBF-linv )
import CSP.Examples.Cardano_network.BlockFetch p as BF
import CSP.Operators {E = BF.BFEv} BF.BFEv-≟ as SrcOpB
import CSP.Rename {E₁ = BF.BFEv} {E₂ = Net_Api Payload} ιBF ιBF⁻¹ ιBF-linv as RenBF

open import Semantics.LTS {E = Net_Api Payload} {I = ExtI (Net_Api Payload)}
  using ( _─[_]─►_; sRet; sSil; sVis; sTau; ev; Event√; Diverges )
open import Semantics.WeakBisim {E = Net_Api Payload} {I = ExtI (Net_Api Payload)}
  using ( _─[τ*]─►_; τ*-refl )
open import Semantics.Refusals {E = Net_Api Payload} {I = ExtI (Net_Api Payload)}
  using ( Offers; deadlock-stable )
open import Semantics.FailureSim {E = Net_Api Payload} {I = ExtI (Net_Api Payload)}
  using ( FSim; fsim→⊑FD )
open import Semantics.FailuresDivergences {E = Net_Api Payload} {I = ExtI (Net_Api Payload)}
  using ( _⊑FD_ )
open import Semantics.BisimFromRel {E = Net_Api Payload} {I = ExtI (Net_Api Payload)}
  using ( module FSimFromRel )
-- for the mechanical orientation check only
open import Semantics.DRImpliesFD {E = Net_Api Payload} {I = ExtI (Net_Api Payload)}
  using ( drbisim→≈FD )

-- the spec tables + `NetTree` + `tableSpec`/`tMenu`, and the DR proof this
-- experiment is compared against (its FORWARD obligations are reused verbatim)
open import CSP.Examples.Cardano_network.NetworkVerification.Liveness.PipePair
open import CSP.Examples.Cardano_network.NetworkVerification.Liveness.PipePairFlipBFs

module CSP.Examples.Cardano_network.NetworkVerification.Liveness.PipePairFlipBFsFSim where

------------------------------------------------------------------------
-- The offer-reflection lemmas: at every STABLE related pair, every visible
-- offer of the spec position is also an offer of the impl state.  This is the
-- ONLY backward information a failures refinement needs — a single-step offer
-- witness, with no residual relation and no τ*-padded weak matching.
------------------------------------------------------------------------

-- spec-offer reflection: every offer of spec position `bsIdle` is an offer of the related impl state
bfsInclIdle : (l : Link) → ∀ (e : Event√ (⊤ {0ℓ})) → Offers (tableSpec (Tbs l) bsIdle) e → Offers (bsI l BF.stIdle) e
bfsInclIdle F.zero _ (_ , sRet ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , keepAlive _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output l′ d′ N2N_BlockFetch} {a = t , m , len , blockFetch (MsgRequestRange r)} refl br)
  with l′ ≟ F.zero | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgStartBatch} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgNoBlocks} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch (MsgBlock _)} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgBatchDone} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output l′ d′ N2N_BlockFetch} {a = t , m , len , blockFetch MsgClientDone} refl br)
  with l′ ≟ F.zero | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , chainSync _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , txSubmission _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , leiosNotify _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , leiosFetch _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_ChainSync} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_TxSubmission} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_KeepAlive} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_LeiosNotify} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , output _ _ N2N_LeiosFetch} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclIdle F.zero _ (_ , sVis {at = _ , break _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sRet ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , keepAlive _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output l′ d′ N2N_BlockFetch} {a = t , m , len , blockFetch (MsgRequestRange r)} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgStartBatch} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgNoBlocks} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch (MsgBlock _)} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgBatchDone} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output l′ d′ N2N_BlockFetch} {a = t , m , len , blockFetch MsgClientDone} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , chainSync _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , txSubmission _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , leiosNotify _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , leiosFetch _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_ChainSync} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_TxSubmission} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_KeepAlive} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_LeiosNotify} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ N2N_LeiosFetch} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclIdle (F.suc F.zero) _ (_ , sVis {at = _ , break _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sRet ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , keepAlive _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output l′ d′ N2N_BlockFetch} {a = t , m , len , blockFetch (MsgRequestRange r)} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgStartBatch} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgNoBlocks} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch (MsgBlock _)} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgBatchDone} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output l′ d′ N2N_BlockFetch} {a = t , m , len , blockFetch MsgClientDone} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , chainSync _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , txSubmission _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , leiosNotify _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , leiosFetch _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_ChainSync} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_TxSubmission} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_KeepAlive} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_LeiosNotify} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ N2N_LeiosFetch} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclIdle (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , break _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sRet ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , keepAlive _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output l′ d′ N2N_BlockFetch} {a = t , m , len , blockFetch (MsgRequestRange r)} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgStartBatch} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgNoBlocks} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch (MsgBlock _)} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , blockFetch MsgBatchDone} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output l′ d′ N2N_BlockFetch} {a = t , m , len , blockFetch MsgClientDone} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , chainSync _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , txSubmission _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , leiosNotify _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_BlockFetch} {a = t , m , len , leiosFetch _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_ChainSync} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_TxSubmission} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_KeepAlive} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_LeiosNotify} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ N2N_LeiosFetch} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclIdle (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , break _} refl ())

-- spec-offer reflection: every offer of spec position `bsBusy` is an offer of the related impl state
bfsInclBusy : (l : Link) → ∀ (e : Event√ (⊤ {0ℓ})) → Offers (tableSpec (Tbs l) bsBusy) e → Offers (bsI l BF.stBusy) e
bfsInclBusy F.zero _ (_ , sRet ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiBF l′ d′ sendBFStartBatch} refl br)
  with l′ ≟ F.zero | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiBF l′ d′ sendBFNoBlocks} refl br)
  with l′ ≟ F.zero | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiBF _ _ sendBFBlock} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiBF _ _ sendBFBatchDone} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiBF _ _ reqBFRange} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclBusy F.zero _ (_ , sVis {at = _ , break _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sRet ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFStartBatch} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFNoBlocks} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ sendBFBlock} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ sendBFBatchDone} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ reqBFRange} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclBusy (F.suc F.zero) _ (_ , sVis {at = _ , break _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sRet ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFStartBatch} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFNoBlocks} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ sendBFBlock} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ sendBFBatchDone} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ reqBFRange} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclBusy (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , break _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sRet ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFStartBatch} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFNoBlocks} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ sendBFBlock} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ sendBFBatchDone} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ reqBFRange} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclBusy (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , break _} refl ())

-- spec-offer reflection: every offer of spec position `bsStream` is an offer of the related impl state
bfsInclStrm : (l : Link) → ∀ (e : Event√ (⊤ {0ℓ})) → Offers (tableSpec (Tbs l) bsStream) e → Offers (bsI l BF.stStreaming) e
bfsInclStrm F.zero _ (_ , sRet ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiBF _ _ sendBFStartBatch} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiBF _ _ sendBFNoBlocks} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiBF l′ d′ sendBFBlock} {a = b} refl br)
  with l′ ≟ F.zero | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiBF l′ d′ sendBFBatchDone} refl br)
  with l′ ≟ F.zero | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiBF _ _ reqBFRange} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclStrm F.zero _ (_ , sVis {at = _ , break _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sRet ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ sendBFStartBatch} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ sendBFNoBlocks} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFBlock} {a = b} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFBatchDone} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ reqBFRange} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclStrm (F.suc F.zero) _ (_ , sVis {at = _ , break _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sRet ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ sendBFStartBatch} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ sendBFNoBlocks} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFBlock} {a = b} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFBatchDone} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ reqBFRange} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclStrm (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , break _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sRet ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ sendBFStartBatch} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ sendBFNoBlocks} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFBlock} {a = b} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF l′ d′ sendBFBatchDone} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ reqBFRange} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclStrm (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , break _} refl ())

-- spec-offer reflection: every offer of spec position `bsAreq r` is an offer of the related impl state
bfsInclAreq : (l : Link) → (r : ChainRange) → ∀ (e : Event√ (⊤ {0ℓ})) → Offers (tableSpec (Tbs l) (bsAreq r)) e → Offers (bsIB l (SrcOpB.Output (BF.apiBFev l hi reqBFRange) r (SrcOpB.Ret (inj₁ BF.stBusy)))) e
bfsInclAreq F.zero r _ (_ , sRet ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiBF _ _ sendBFStartBatch} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiBF _ _ sendBFNoBlocks} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiBF _ _ sendBFBlock} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiBF _ _ sendBFBatchDone} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} {a = x} refl br)
  with l′ ≟ F.zero | d′ ≟ hi
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} {a = x} refl br) | yes refl | yes refl
  with x ≟ r | br
... | yes refl | refl = _ , sVis refl ((bfAreqImpl F.zero) r)
... | no _     | ()
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} refl br) | yes refl | no _ = case br of λ ()
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} refl br) | no _     | _    = case br of λ ()
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclAreq F.zero r _ (_ , sVis {at = _ , break _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sRet ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiBF _ _ sendBFStartBatch} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiBF _ _ sendBFNoBlocks} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiBF _ _ sendBFBlock} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiBF _ _ sendBFBatchDone} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} {a = x} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} {a = x} refl br) | yes refl | yes refl
  with x ≟ r | br
... | yes refl | refl = _ , sVis refl ((bfAreqImpl (F.suc F.zero)) r)
... | no _     | ()
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} refl br) | yes refl | no _ = case br of λ ()
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} refl br) | no _     | _    = case br of λ ()
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclAreq (F.suc F.zero) r _ (_ , sVis {at = _ , break _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sRet ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiBF _ _ sendBFStartBatch} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiBF _ _ sendBFNoBlocks} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiBF _ _ sendBFBlock} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiBF _ _ sendBFBatchDone} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} {a = x} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} {a = x} refl br) | yes refl | yes refl
  with x ≟ r | br
... | yes refl | refl = _ , sVis refl ((bfAreqImpl (F.suc (F.suc F.zero))) r)
... | no _     | ()
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} refl br) | yes refl | no _ = case br of λ ()
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} refl br) | no _     | _    = case br of λ ()
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclAreq (F.suc (F.suc F.zero)) r _ (_ , sVis {at = _ , break _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sRet ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiBF _ _ sendBFRequestRange} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiBF _ _ sendBFClientDone} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiBF _ _ sendBFStartBatch} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiBF _ _ sendBFNoBlocks} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiBF _ _ sendBFBlock} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiBF _ _ sendBFBatchDone} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiBF _ _ recvBFBlock} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} {a = x} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} {a = x} refl br) | yes refl | yes refl
  with x ≟ r | br
... | yes refl | refl = _ , sVis refl ((bfAreqImpl (F.suc (F.suc (F.suc F.zero)))) r)
... | no _     | ()
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} refl br) | yes refl | no _ = case br of λ ()
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiBF l′ d′ reqBFRange} refl br) | no _     | _    = case br of λ ()
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclAreq (F.suc (F.suc (F.suc F.zero))) r _ (_ , sVis {at = _ , break _} refl ())

-- spec-offer reflection: every offer of spec position `bsDdone` is an offer of the related impl state
bfsInclDdone : (l : Link) → ∀ (e : Event√ (⊤ {0ℓ})) → Offers (tableSpec (Tbs l) bsDdone) e → Offers (bsIB l (SrcOpB.Prefix₀ (BF.doneBF l hi) (SrcOpB.Ret (inj₁ BF.stDone)))) e
bfsInclDdone F.zero _ (_ , sRet ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , done l′ d′ N2N_BlockFetch} refl br)
  with l′ ≟ F.zero | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclDdone F.zero _ (_ , sVis {at = _ , done _ _ N2N_ChainSync} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , done _ _ N2N_TxSubmission} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , done _ _ N2N_KeepAlive} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , done _ _ N2N_LeiosNotify} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , done _ _ N2N_LeiosFetch} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclDdone F.zero _ (_ , sVis {at = _ , break _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sRet ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , done l′ d′ N2N_BlockFetch} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , done _ _ N2N_ChainSync} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , done _ _ N2N_TxSubmission} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , done _ _ N2N_KeepAlive} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , done _ _ N2N_LeiosNotify} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , done _ _ N2N_LeiosFetch} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclDdone (F.suc F.zero) _ (_ , sVis {at = _ , break _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sRet ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done l′ d′ N2N_BlockFetch} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done _ _ N2N_ChainSync} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done _ _ N2N_TxSubmission} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done _ _ N2N_KeepAlive} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done _ _ N2N_LeiosNotify} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done _ _ N2N_LeiosFetch} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclDdone (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , break _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sRet ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done l′ d′ N2N_BlockFetch} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi | br
... | yes refl | yes refl | refl = _ , sVis refl refl
... | yes refl | no _     | ()
... | no _     | _        | ()
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done _ _ N2N_ChainSync} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done _ _ N2N_TxSubmission} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done _ _ N2N_KeepAlive} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done _ _ N2N_LeiosNotify} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done _ _ N2N_LeiosFetch} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclDdone (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , break _} refl ())

-- spec-offer reflection: every offer of spec position `bsWsb` is an offer of the related impl state
bfsInclWsb : (l : Link) → ∀ (e : Event√ (⊤ {0ℓ})) → Offers (tableSpec (Tbs l) bsWsb) e → Offers (bsIB l (SrcOpB.Output (BF.sendBF l hi) valSB (SrcOpB.Ret (inj₁ BF.stStreaming)))) e
bfsInclWsb F.zero _ (_ , sRet ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ F.zero | d′ ≟ hi
bfsInclWsb F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valSB | br
... | yes refl | refl = _ , sVis refl (bfWsbImpl F.zero)
... | no _     | ()
bfsInclWsb F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWsb F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWsb F.zero _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWsb F.zero _ (_ , sVis {at = _ , break _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sRet ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valSB | br
... | yes refl | refl = _ , sVis refl (bfWsbImpl (F.suc F.zero))
... | no _     | ()
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWsb (F.suc F.zero) _ (_ , sVis {at = _ , break _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sRet ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valSB | br
... | yes refl | refl = _ , sVis refl (bfWsbImpl (F.suc (F.suc F.zero)))
... | no _     | ()
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWsb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , break _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sRet ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valSB | br
... | yes refl | refl = _ , sVis refl (bfWsbImpl (F.suc (F.suc (F.suc F.zero))))
... | no _     | ()
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWsb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , break _} refl ())

-- spec-offer reflection: every offer of spec position `bsWnb` is an offer of the related impl state
bfsInclWnb : (l : Link) → ∀ (e : Event√ (⊤ {0ℓ})) → Offers (tableSpec (Tbs l) bsWnb) e → Offers (bsIB l (SrcOpB.Output (BF.sendBF l hi) valNB (SrcOpB.Ret (inj₁ BF.stIdle)))) e
bfsInclWnb F.zero _ (_ , sRet ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ F.zero | d′ ≟ hi
bfsInclWnb F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valNB | br
... | yes refl | refl = _ , sVis refl (bfWnbImpl F.zero)
... | no _     | ()
bfsInclWnb F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWnb F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWnb F.zero _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWnb F.zero _ (_ , sVis {at = _ , break _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sRet ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valNB | br
... | yes refl | refl = _ , sVis refl (bfWnbImpl (F.suc F.zero))
... | no _     | ()
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWnb (F.suc F.zero) _ (_ , sVis {at = _ , break _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sRet ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valNB | br
... | yes refl | refl = _ , sVis refl (bfWnbImpl (F.suc (F.suc F.zero)))
... | no _     | ()
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWnb (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , break _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sRet ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valNB | br
... | yes refl | refl = _ , sVis refl (bfWnbImpl (F.suc (F.suc (F.suc F.zero))))
... | no _     | ()
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWnb (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , break _} refl ())

-- spec-offer reflection: every offer of spec position `bsWblk b` is an offer of the related impl state
bfsInclWblk : (l : Link) → (b : Block) → ∀ (e : Event√ (⊤ {0ℓ})) → Offers (tableSpec (Tbs l) (bsWblk b)) e → Offers (bsIB l (SrcOpB.Output (BF.sendBF l hi) (valBLK b) (SrcOpB.Ret (inj₁ BF.stStreaming)))) e
bfsInclWblk F.zero b _ (_ , sRet ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ F.zero | d′ ≟ hi
bfsInclWblk F.zero b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ (valBLK b) | br
... | yes refl | refl = _ , sVis refl ((bfWblkImpl F.zero) b)
... | no _     | ()
bfsInclWblk F.zero b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWblk F.zero b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWblk F.zero b _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWblk F.zero b _ (_ , sVis {at = _ , break _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sRet ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ (valBLK b) | br
... | yes refl | refl = _ , sVis refl ((bfWblkImpl (F.suc F.zero)) b)
... | no _     | ()
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWblk (F.suc F.zero) b _ (_ , sVis {at = _ , break _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sRet ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ (valBLK b) | br
... | yes refl | refl = _ , sVis refl ((bfWblkImpl (F.suc (F.suc F.zero))) b)
... | no _     | ()
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWblk (F.suc (F.suc F.zero)) b _ (_ , sVis {at = _ , break _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sRet ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ (valBLK b) | br
... | yes refl | refl = _ , sVis refl ((bfWblkImpl (F.suc (F.suc (F.suc F.zero)))) b)
... | no _     | ()
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWblk (F.suc (F.suc (F.suc F.zero))) b _ (_ , sVis {at = _ , break _} refl ())

-- spec-offer reflection: every offer of spec position `bsWbd` is an offer of the related impl state
bfsInclWbd : (l : Link) → ∀ (e : Event√ (⊤ {0ℓ})) → Offers (tableSpec (Tbs l) bsWbd) e → Offers (bsIB l (SrcOpB.Output (BF.sendBF l hi) valBD (SrcOpB.Ret (inj₁ BF.stIdle)))) e
bfsInclWbd F.zero _ (_ , sRet ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ F.zero | d′ ≟ hi
bfsInclWbd F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valBD | br
... | yes refl | refl = _ , sVis refl (bfWbdImpl F.zero)
... | no _     | ()
bfsInclWbd F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWbd F.zero _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWbd F.zero _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWbd F.zero _ (_ , sVis {at = _ , break _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sRet ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc F.zero) | d′ ≟ hi
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valBD | br
... | yes refl | refl = _ , sVis refl (bfWbdImpl (F.suc F.zero))
... | no _     | ()
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWbd (F.suc F.zero) _ (_ , sVis {at = _ , break _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sRet ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc (F.suc F.zero)) | d′ ≟ hi
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valBD | br
... | yes refl | refl = _ , sVis refl (bfWbdImpl (F.suc (F.suc F.zero)))
... | no _     | ()
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWbd (F.suc (F.suc F.zero)) _ (_ , sVis {at = _ , break _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sRet ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br)
  with l′ ≟ (F.suc (F.suc (F.suc F.zero))) | d′ ≟ hi
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} {a = pl} refl br) | yes refl | yes refl
  with pl ≟ valBD | br
... | yes refl | refl = _ , sVis refl (bfWbdImpl (F.suc (F.suc (F.suc F.zero))))
... | no _     | ()
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | yes refl | no _ = case br of λ ()
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input l′ d′ N2N_BlockFetch} refl br) | no _     | _    = case br of λ ()
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_ChainSync} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_TxSubmission} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_KeepAlive} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_LeiosNotify} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , input _ _ N2N_LeiosFetch} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , output _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , done _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiBF _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiCS _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiKA _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiTS _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLN _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , apiLF _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndmsg _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvmsg _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , tx _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , sndack _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , rcvack _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , ack _ _ _} refl ())
bfsInclWbd (F.suc (F.suc (F.suc F.zero))) _ (_ , sVis {at = _ , break _} refl ())

------------------------------------------------------------------------
-- The `FSimFromRel` stability obligation.  The spec is a τ-free `tableSpec`
-- FSM, so the spec's τ*-run is always `τ*-refl` and the settled state is the
-- spec position itself (`λ _ _ → refl` proves `isStable` of a non-final table
-- node).  The five UNSTABLE impl states (four loop-re-entry `sil`s and the
-- terminated `ret`) discharge the hypothesis by `lower`.
------------------------------------------------------------------------

-- whenever the impl is stable, the spec settles at once with a smaller menu
bfsStab : (l : Link) → ∀ {p q} → BFSRel l p q → isStable p
        → Σ[ q′ ∈ NetTree ]
            ( (q ─[τ*]─► q′) × isStable q′
            × (∀ (e : Event√ (⊤ {0ℓ})) → Offers q′ e → Offers p e) )
bfsStab l sIdle      _  = _ , τ*-refl , (λ _ _ → refl) , bfsInclIdle l
bfsStab l sBusy      _  = _ , τ*-refl , (λ _ _ → refl) , bfsInclBusy l
bfsStab l sStrm      _  = _ , τ*-refl , (λ _ _ → refl) , bfsInclStrm l
bfsStab l (iAreq r)  _  = _ , τ*-refl , (λ _ _ → refl) , bfsInclAreq l r
bfsStab l iDdone     _  = _ , τ*-refl , (λ _ _ → refl) , bfsInclDdone l
bfsStab l iWsb       _  = _ , τ*-refl , (λ _ _ → refl) , bfsInclWsb l
bfsStab l iWnb       _  = _ , τ*-refl , (λ _ _ → refl) , bfsInclWnb l
bfsStab l (iWblk b)  _  = _ , τ*-refl , (λ _ _ → refl) , bfsInclWblk l b
bfsStab l iWbd       _  = _ , τ*-refl , (λ _ _ → refl) , bfsInclWbd l
bfsStab l sDead      _  = _ , τ*-refl , deadlock-stable , λ _ off → off
bfsStab l mIdle      st = ⊥-elim (lower st)
bfsStab l mBusy      st = ⊥-elim (lower st)
bfsStab l mStrm      st = ⊥-elim (lower st)
bfsStab l mDone      st = ⊥-elim (lower st)
bfsStab l sDone      st = ⊥-elim (lower st)

-- the ONE-WAY coinduction principle: forward steps + stability + impl-divergence
module BFSFS (l : Link) = FSimFromRel (BFSRel l) (bfsFwdE l) (bfsFwdT l) (bfsStab l) (bfsNdivL l)

-- the BF server spec failure-simulates the renamed BF server iter
bfServerFSim : (l : Link) → FSim (⊤ {0ℓ}) (BFserverA l hi) (bfServerSpec l hi)
bfServerFSim l = BFSFS.rel→fsim l sIdle

-- the one-way half of `bfServer≈DRhi`, via FSim only
bfServerSpec⊑FD : (l : Link) → bfServerSpec l hi ⊑FD BFserverA l hi
bfServerSpec⊑FD l = fsim→⊑FD (bfServerFSim l)

-- mechanical confirmation that this is the SECOND component of the ≈FD result
orientation-check : (l : Link) → bfServerSpec l hi ⊑FD BFserverA l hi
orientation-check l = proj₂ (drbisim→≈FD (bfServer≈DRhi l))
